name: build

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Free Pascal
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq fpc >/dev/null
      - name: Show compiler
        run: |
          fpc -iV
          ls /usr/lib/fpc/*/units/*/rtl/ 2>/dev/null | head
